### ISSUE TITLE
Drag n Drop within a tree with keyboard support

### ISSUE THREAD

**Issue by sanjeevbaral** [vakata/jstree-php-demos#1]
I am thinking of using JSTree for a project I am currently working on. I have just been reading upon it and looking at samples for past couple of days and I see that this will work great for most functionalities required. Just a few questions since I have not seen any samples illustrating if such a thing can be done.

I need to be able to drag a node and drop it on another node but I need to control how the dropped node behaves:
--------------------------------------------------------------------
1. when the node is dragged and dropped without any key being pressed I want the dropped node to be the last child of the target node.
2. when the node is dragged and dropped while the ctrl key is pressed I want the dropped node to be the previous sibling of the target node.
3. when the node is dragged and dropped while the shift key is pressed I want the dropped node to be the next sibling of the target node.

Can you give me some ideas about how I can do such a thing?

**Comment by vakata** [comment]
You can use the ```core.check_callback``` function and while monitoring for pressed keys prevent all other kinds of drops. When a node is dragged this function will be triggered 3 times - checking if the node can be dropped inside, before or after the target node - depending on your requirements return ```true`'` only for the valid drop. Keep in mind the function will be triggered in other cases too, so check if this is a move_node or copy_node operation.
Here are the docs:
https://www.jstree.com/api/#/?q=check&f=$.jstree.defaults.core.check_callback

You might want to set ```dnd.copy``` to ```false``` as well:
https://www.jstree.com/api/#/?q=dnd&f=$.jstree.defaults.dnd.copy
