### ISSUE TITLE
adding nodes per js

### ISSUE THREAD

**Issue by transfluxus** [vakata/jstree-php-demos#2]
I want to add nodes per js.
I found this fiddle but it doesn't work anymore

https://jsfiddle.net/3q9Ma/223/

when I go through the code with the debugger
```
if(!this.check("create_node", node, par, pos)) {
				this.settings.core.error.call(this, this._data.core.last_error);
				return false;
			}
```

I'm calling
`jst.create_node(jst.get_selected()[0])`

**Comment by vakata** [comment]
Set ```core.check_callback``` to ```true```. As stated in the docs - unless this is set all structure modifications are prevented.
